[package]
name = "rs-multimodal-llm"
version = "0.1.0"
edition = "2021"

[dependencies]
llama-cpp-2 = { path = "../llama-cpp-rs/llama-cpp-2", features = ["mtmd", "cuda"] }
llama-cpp-sys-2 = { path = "../llama-cpp-rs/llama-cpp-sys-2" }
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
image = "0.24"
